### ISSUE TITLE
iTunes stopped working

### ISSUE THREAD

**Issue by kopytko95** [StigNygaard/Stigs_Art_Grabr#1]
Hi,

you've mentioned on the script page you wouldn't mind to be informed if something happens, so...
iTunes changed its layout completely (good thing is 500x500 images can be downloaded on right-click, bad thing is script stopped working)
Also side question - would it be possible to make this script work on spotify or is that not an option?

**Comment by StigNygaard** [comment]
Hi @kopytko95 
Thanks for the tip. I haven't used Grabr myself in a long period, so I didn't know about iTunes problems. I look into it soon and see if it can be fixed.
I don't know about Spotify. It requires I can find some information on "file patterns" for their various sizes (or can guess). I will give it a look, but absolutely no promises :-)

**Comment by StigNygaard** [comment]
Btw, Art Grabr might not be working directly on the iTunes / Apple Music site at the moment. But Grabr also supports some search-engines for the Apple site, and Grabr still seems to be working on these:

http://musicdiner.com/
https://fnd.io/
http://labs.stephenou.com/itunes/

But I hope to find time to look at the support for the  iTunes / Apple Music site itself in the upcoming weekend...

**Comment by StigNygaard** [comment]
Hi @kopytko95 
I have just released an updated version 2020.04.25.0 of Grabr here and on Greasy Fork.
It seems to fix Grabr support on the Danish version of Apple Music, but some times there are local variations of the Apple site. Please let me know if it works for you?

**Comment by kopytko95** [comment]
i've checked for Polish, American, German, Chinese and Bhutanese (just to be sure) and works perfectly, thanks a lot!

**Comment by StigNygaard** [comment]
Thanks @kopytko95 
Regarding Spotify, I have not been able to find out how or if it is possible to find larger cover art images than those low-res images already displayed. But if someone finds out how to change path/name to a low-res image, to a path/name pointing to a high-res version of same image instead, I would be happy to get the tip.
