### ISSUE TITLE
Grabbing artwork from Spotify

### ISSUE THREAD

**Issue by kopytko95** [StigNygaard/Stigs_Art_Grabr#3]
Hi, I've already posted here about iTunes issue.. You've mentioned that if someone finds pattern, then you'd look into it. i don't know, maybe it's too good to be true, but:

I've felt adventurous today checked few random spotify releases for low and high-res covers and:
https://i.scdn.co/image/ab67616d00001e0226d0e7dcdb9154b1cee461a8
https://i.scdn.co/image/ab67616d0000b27326d0e7dcdb9154b1cee461a8

https://i.scdn.co/image/ab67616d00001e02a627aa9d60427b172e960264
https://i.scdn.co/image/ab67616d0000b273a627aa9d60427b172e960264

https://i.scdn.co/image/ab67616d00001e025b8249aba05ec65a7c47d8fc
https://i.scdn.co/image/ab67616d0000b2735b8249aba05ec65a7c47d8fc

https://i.scdn.co/image/ab67616d00001e028863bc11d2aa12b54f5aeb36
https://i.scdn.co/image/ab67616d0000b2738863bc11d2aa12b54f5aeb36

https://i.scdn.co/image/ab67616d00001e026105bf671731aa08830e9a86
https://i.scdn.co/image/ab67616d0000b2736105bf671731aa08830e9a86

First of two is always low-res, and second is high res. Apparently, if 1e02 gets replace with b273, then we get image 640x640 instead of regular 300x300

Is it maybe what you needed?

**Comment by StigNygaard** [comment]
Cool. It seems to work. I should be able to implement something based on this. I'll put it on my todo-list, and expect to give it a look in one of the coming weeks.
And just to be sure, you are thinking about when browsing https://open.spotify.com ? Or are there other webaddresses where you can find cover-art from Spotify?

**Comment by kopytko95** [comment]
Yeah, I am thinking about https://open.spotify.com

**Comment by StigNygaard** [comment]
@kopytko95 

Support, or at least partial support for open.spotify.com has been added to latest version 2020.05.30.1.
To be able to get cover images, Art Grabr should be executed on an "album-page" (including some, but not all, playlist pages). 

Users of GreaseMonkey on Firefox who needs to activate Art Grabr from context-menu, will experience that Spotify site default blocks the right-click context menu. However if you hold down shift-key while right-clicking on page, Firefox will still open the context-menu.

**Comment by kopytko95** [comment]
Thanks! Love it
