### ISSUE TITLE
iTunes doesn't work

### ISSUE THREAD

**Issue by kopytko95** [StigNygaard/Stigs_Art_Grabr#4]
Hi! It's me again

Something happened so that script does not work for releases' image on iTunes page. At the same time script still works on suggested releases (image attached)
https://ibb.co/L0ZzndR
Could you please take look at it?

Thanks in advance!
CK

**Comment by StigNygaard** [comment]
Yes, I can see it doesn't work everywhere. I'll give it a look. 
Thanks for reporting.

**Comment by StigNygaard** [comment]
Hi @kopytko95 
I think I managed to do a really quick fix. Try updating. It should work better now with just released version 2020.07.02.0.
Let me know if it works for you. Only had time to very quick testing before I had to leave PC for today :-) ...

**Comment by kopytko95** [comment]
It's perfect, thanks a lot! <3

**Comment by StigNygaard** [comment]
Thanks. Closing issue.
