### ISSUE TITLE
Changelog appended to some MusicBrainz pages

### ISSUE THREAD

**Issue by loucasal** [StigNygaard/Stigs_Art_Grabr#6]
Hi Stig,

The Art Grabr changelog is displayed at the end of some MusicBrainz pages for me (see screenshot).
The issue /may/ be triggered by the presence of open text fields (as I can see it when editing my profile, sending an email to a user or reporting a user, which all have at least one of those).

![screenshot](https://user-images.githubusercontent.com/25279797/102141174-b3d81f00-3e60-11eb-8f82-058522a8df97.png)

**Comment by StigNygaard** [comment]
Hi @loucasal 
Thanks for reporting. Weird indeed.
If not before, I hope to get some time between Christmas and New Year to give Art Grabr an update.  I think it is starting to need it :-/

**Comment by loucasal** [comment]
Thanks! I forgot to add - I am using the script on Firefox 83 running Violentmonkey.

**Comment by StigNygaard** [comment]
Hi @loucasal 
Should be fixed in the just released version 2020.12.28.0.

**Comment by loucasal** [comment]
Verified, thanks!
