### ISSUE TITLE
Deezer stopped working

### ISSUE THREAD

**Issue by fen0x** [StigNygaard/Stigs_Art_Grabr#7]
Some changes in Deezer HTML may have broken the grabber.

**Comment by StigNygaard** [comment]
Thanks for reporting @fen0x .
I haven't used Grabr myself or verified the functionality for some time. But I hope to do some work on the tool after Christmas. Seems functionality are broken on several sites right now.

**Comment by StigNygaard** [comment]
Hi @fen0x 
I just tried current Grabr on Deezer. Seems to work for me. Do you still have problems?
Any specific pages not working?

**Comment by fen0x** [comment]
Hi @StigNygaard!
I have the same version but I just realized that the problem is not on Deezer but the version of my browser: Firefox 85.0b4.
There's no context menu anymore, but using the Tampermonkey menu it works as usual.
Thanks a lot for your effort!

**Comment by StigNygaard** [comment]
Hi @fen0x 
Good to hear. Yes from Firefox 85 Mozilla has removed support for the "HTML5 menus" (#8). That's a pity, but not much I (easily) can do about it.
